### ISSUE TITLE
Version 1.19.0 breaks compatibility with json_rspec

### ISSUE THREAD

**Issue by totus** [sferik/multi_json#56]
After updating the gem to 1.19.0, the tests start to fail with
```
      Failure/Error: expect(response.body).to be_json_eql(not_found_exception.message.to_json).at_path('errors/message')

      NoMethodError:
        undefined method 'decode' for module MultiJson
```

As `load`/`decode` are now private functions.

Minimal reproduction scenario is to have `json_rspec` and `multi_json` gems and have a test with:
```
it 'compares json' do
  json = '{}'
  expect(json).to be_json_eql(json)
end
```

**Comment by sferik** [comment]
I'm working on a fix for this now.

**Comment by totus** [comment]
@sferik, thanks a lot, have an awesome holiday season!
